version: '3'

services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: backend.dockerfile
    env_file: .env
    restart: always
    ports:
      - 8001:8001
    depends_on:
      - postgres
    networks:
      - database
      - default

  postgres:
    container_name: database
    image: postgres:15.1-alpine
    restart: always
    env_file: .env
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - database

  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: frontend.dockerfile
    restart: always
    ports:
      - 81:80

volumes:
  postgres:

networks:
  database:
